import json
import sys
import os

# Read rebuilt NDJSON
try:
    with open('kibana/dashboards.ndjson', 'r', encoding='utf-8') as f:
        rebuilt_json = json.loads(f.readline().strip())
        rebuilt_panels_str = rebuilt_json['attributes']['panelsJSON']
except Exception as e:
    print("Error reading dashboards.ndjson", e)
    sys.exit(1)

# Read original literal string
try:
    # We'll just read temp_original_panels.json which contains EXACTLY the literal string!
    with open('temp_original_panels.json', 'r', encoding='utf-8') as f:
        original_panels_str = f.read()
except Exception as e:
    print("Error reading temp_original_panels.json", e)
    sys.exit(1)

# Check lengths
print(f"Original length: {len(original_panels_str)}")
print(f"Rebuilt length: {len(rebuilt_panels_str)}")

# Since rebuilt_panels_str is generated by json.dumps(), it might have spaces.
# Let's parse both and see if they are semantically identical
try:
    # Wait, the whole issue was that original_panels_str CANNOT be parsed by json.loads()!
    o_parsed = json.loads(original_panels_str)
    print("Original string CAN be parsed by json.loads!")
except Exception as e:
    print("Original string CANNOT be parsed by json.loads:", e)

# Let's find exactly where the rebuilt string differs from original
# First, let's just write them to disk so we can see
with open('rebuilt_panels_str.txt', 'w', encoding='utf-8') as f:
    f.write(rebuilt_panels_str)
with open('original_panels_str.txt', 'w', encoding='utf-8') as f:
    f.write(original_panels_str)

print("Strings exported. Please diff them.")
